// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnokrqabnkvbjcquokfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRub2tycWFibmt2YmpjcXVva2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTg1NTcsImV4cCI6MjA3Mzc5NDU1N30.h_bwHDAq9PjBlacmGVsyXyGLXBzXRCrIjSp0bi2nWIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});